account/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
]

either/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('question.urls')),  # questions url이 포함되면 question.urls에 있는 주소를 불러옴
    path('accounts/', include('account.urls')),
]

question/urls.py
from django.urls import path
from . import views

app_name = 'question'

urlpatterns = [
    path('', views.list, name='list'),
    path('create/', views.create, name='create'),   # 앞에는 모두 questions가 생략되어 있음
    path('<int:id>/detail/', views.detail, name='detail'),
    path('<int:id>/comment/create', views.comment_create, name='comment_create'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    # path('<int:id>/comment/update', views.comment_update, name='comment_update'),
    # path('<int:id>/comment/delete', views.comment_delete, name='comment_delete'),
]

question/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Question(models.Model):  # models.Model을 상속받음
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  
    title = models.CharField(max_length=50)            # 필수 작성 사항 -> AUTH_USER_MODEL = auth.user(기본 user 모델 사용)
    answerA = models.CharField(max_length=50)
    answerB = models.CharField(max_length=50)
    
    def __str__(self):
        return self.title  # 오버라이드

class Comment(models.Model):                                        # 2번을 선택했을 때
    question = models.ForeignKey(Question, on_delete=models.CASCADE)   # 질문이 사라지면 댓글도 모두 사라진다
    answer_list = [['A', 'left'], ['B', 'right']]   # 사용자가 어떤 선택을 할 수 있는지 선택지 제공
    answer = models.CharField(max_length=50, choices=answer_list)
    content = models.CharField(max_length=50)

    def __str__(self):
        return self.content

question/forms.py
from django import forms
from .models import Question, Comment   # 현재 폴더 아래 있는 Question class를 import시켜 model에 넣음

class QuestionForm(forms.ModelForm):   # forms의 ModelForm을 상속시킴
    class Meta:
        model = Question
        fields = ['title', 'answerA', 'answerB']
        
class CommentForm(forms.ModelForm):
    class Meta:       
        model = Comment
        fields = ['answer', 'content']  # id가 없어서 저장 불가 

question/views.py
from django.shortcuts import render, redirect, resolve_url
from question.forms import QuestionForm, CommentForm   # QuestionForm class를 가져옴
from .models import Question
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib.auth.decorators import login_required

# Create your views here.
def list(request):
    # questions = Question.objects.all()  # 전체 목록을 보여주는 코드 -> 모든 질문을 가져옴
    questions_list = Question.objects.all()
    paginator = Paginator(questions_list, 5)  # 페이지 당 5개씩 끊음

    page = request.GET.get('page')
    questions = paginator.get_page(page)
    # return render(request, 'list.html', {'contacts': contacts})
    
    return render(request, 'question/list.html', {'questions':questions})  # 자동으로 감지하지 못하고 설정 필요

@login_required
def create(request):   # 에러 페이지의 모든 데이터는 request에 저장되어 전달된다
    if request.method == "POST":
        # 데이터를 저장하는 로직 - post 방식으로 넘어와야 데이터를 DB에 저장
        form = QuestionForm(request.POST)   # 사용자가 입력한 내용을 폼에 넣어 저장
        if form.is_valid():   # 빈 데이터나 형식에 맞지 않는지 검증
            question = form.save(commit=False)
            question.user = request.user  # user 정보(로그인이 된 사람만 가능)
            question.save()
            return redirect(resolve_url('question:list'))
    else:  # GET 방식
        # 사용자에게 폼을 만들어 전달
        form = QuestionForm()   # 웹페이지가 직접 폼 내용을 자동으로 담아 건네줌
    return render(request, 'question/create.html', {'form': form})

@login_required
def detail(request, id):
    question = Question.objects.get(id=id)
    form = CommentForm(initial={'question':id})  # question의 값을 id로 넘김 -> 특정 title에 대한 댓글을 달아 넘길 수 있음
    A = question.comment_set.all().filter(answer="A")
    B = question.comment_set.all().filter(answer="B")
    
    if len(A) + len(B) == 0:
        A_per = 0
        B_per = 0
    else:
        A_per = len(A) / (len(A) + len(B)) * 100
        B_per = len(B) / (len(A) + len(B)) * 100
    
    return render(request, 'question/detail.html', {'question': question, 'form': form, 'A': A, 'B': B, 'A_per':A_per, 'B_per':B_per})
    
    
def comment_create(request, id):
    if request.method == "POST":
        # 저장하기
        form = CommentForm(request.POST)  # request.POST에 사용자가 입력한 정보 저장됨
        if form.is_valid():
            comment = form.save(commit=False)  # save는 add와 commit이 가능한데, add만 가능
            comment.question = Question.objects.get(id=id)  # id 베이스로 Question을 찾고 comment.question에 저장
            comment.save()
            return redirect(resolve_url('question:detail', id))   # 댓글을 단 title 페이지 보여주기
        
    else:  # GET 방식 요청
        # form = CommentForm()  # comment만 만드는 페이지가 없어 detail로 연결 - 문제는 comment만 넣는 페이지가 없어 redirect함
        return redirect(resolve_url('question:detail', id))
    return render(request, 'question/detail.html', {'form':form})


def update(request, id):
    question = Question.objects.get(id=id)
    
    if request.method == 'POST':
        # 업데이트 로직
        form = QuestionForm(request.POST, instance=question)  # instance와 비교해 POST를 통해 바꾸기
        if form.is_valid():
            form.save()
            return redirect(resolve_url('question:detail', id))
    else:
        # 폼 보여주기
        form = QuestionForm(instance=question)  # 사용자가 기존에 넣었던 데이터를 출력함
    return render(request, 'question/update.html', {'form':form, 'question':question})
    
def delete(request, id):
    question = Question.objects.get(id=id)
    question.delete()
    return redirect(resolve_url('question:list'))


# def comment_update(request, id):
#     comment = Comment.objects.get(id=id)

#     if request.method == "POST":
#         form = CommentForm(request.POST, instance=comment)
#         if comment.is_valid():
#             comment.save
#             return redirect(resolve_url('comment:detail', id))
#     else:
#         form = CommentForm(instance=comment)
#     return render(request, 'question/update.html', {'comment':comment})


# def comment_delete(request, id):
#     comment = Comment.objects.get(id=id)
#     comment.delete()
#     return redirect(resolve_url('comment:list'))
    

question/templates/question/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <a href="{% url 'question:create' %}">글 생성</a>
    <div class="container">
        {% if user.is_authenticated %}  <!--user가 로그인한 상태인가?-->
            <!--로그아웃 버튼-->
            <a href="{% url 'account:logout' %}">로그아웃</a>
        {% else %}
            <!--로그인 버튼-->
            <a href="{% url 'account:login' %}">로그인</a>
        {% endif %}
        
        {% block body_block %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

question/templates/question/create.html
{% extends 'question/base.html' %}

{% block body_block %}
    <form action="{% url 'question:create' %}" method="post">
        {% csrf_token %}
        <table>
        {{form.as_table}}  <!--as_p는 한 줄씩 떨어져서 묶음-->
        </table>
        <input type="submit"/>
    </form>
{% endblock %}

question/templates/question/detail.html
{% extends 'question/base.html' %}

{% block body_block %}
    
    <h1>{{question.user}}</h1>
    <h1>{{question.title}}</h1>
    <a href="{% url 'question:update' id=question.id %}">수정</a>
    <a href="{% url 'question:delete' id=question.id %}">삭제</a>
    <h3>{{question.answerA}} : {{A|length}} VS {{question.answerB}} : {{B|length}}</h3>  <!--A와 B의 댓글 갯수 보여줌-->
   
    <div class="progress">                                                                              <!--소수점 1자리만 표시-->
      <div class="progress-bar" role="progressbar" style="width: {{A_per}}%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{A_per|floatformat}}%</div>
      <div class="progress-bar bg-success" role="progressbar" style="width: {{B_per}}%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">{{B_per|floatformat}}%</div>
    </div>
                       <!--/questions/1/comment/create-->
    <form action="{% url 'question:comment_create' question.id %}" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
    
    <!--{% for comment in question.comment_set.all %}   <!--question이 가지고 있는 comment의 집합들 출력-->-->
    <!--    <h5>{{comment.answer}}</h5>-->
    <!--    <p>{{comment.content}}</p>-->
    <!--    <a href="{% url 'question:update' id=comment.id %}">수정</a>-->
    <!--    <a href="{% url 'question:delete' id=comment.id %}">삭제</a>-->
    <!--{% endfor %}-->

{% endblock %}

question/templates/question/list.html
{% extends 'question/base.html' %}

{% block body_block %}

{% load bootstrap_pagination %}

    <h1>여기는 list입니다.</h1>
    <h1>{{Profile.user}}님 환영합니다.</h1>
    
    {% for question in questions %}
        <h1>{{question.title}}</h1>
        <a href="{% url 'question:detail' id=question.id %}">글보기</a>
    {% endfor %}
    {% bootstrap_paginate questions range=5 show_first_last=True %}

{% endblock %}

question/templates/question/update.html
{% extends 'question/base.html' %}

{% block body_block %}
    <form action="{% url 'question:update' id=question.id %}" method='post'>  <!--{url 'app_name:name' id=}-->
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
    
    <!--{% for comment in question.comment_set.all %}-->
    <!--    <form action="{% url 'question:update' id=comment.id %}" method='post'>-->
    <!--        {% csrf_token %}-->
    <!--        {{form.as_p}}-->
    <!--        <input type="submit">-->
    <!--    </form>-->
    <!--{% endfor %}-->
    
{% endblock %}